#pragma once


#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_CURVED_OVERLAY

#define TAPPING_TERM 200
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

